services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "4200:80"
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:8080
    networks:
      - loanadmin_frontendBackend

  backend:
    build: ./backend
    volumes:
      - ./backend/src:/app/src
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - "8080:8080"
    networks:
      - loanadmin_frontendBackend

networks:
  loanadmin_frontendBackend:
    driver: bridge