services:
  loanfrontend:
    build: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - loan_app_backend
    environment:
      - API_URL=http://localhost:8080
  loan_app_backend:
    build: ./backend
    ports:
      - "8080:8080"